import type { DomainMatch } from '~/composables/features/useDomainFinder'
import { generateJobSearchQueries, type QuerySet } from '~/utils/queryGenerator'

export const useJobSearchQueryGenerator = () => {
  const querySets = ref<QuerySet[]>([])
  const isGenerating = ref(false)
  const copySuccess = ref(false)

  /**
   * Generate job search queries for selected domains
   */
  const generateQueries = (domains: DomainMatch[]): QuerySet[] => {
    isGenerating.value = true

    try {
      const generated = generateJobSearchQueries(
        domains.map(d => ({
          technical_role: d.technical_role,
          industry: d.industry,
          domain_name: d.domain_name
        }))
      )

      querySets.value = generated
      return generated
    } finally {
      isGenerating.value = false
    }
  }

  /**
   * Copy a single query to clipboard
   */
  const copyToClipboard = async (query: string): Promise<boolean> => {
    try {
      if (navigator.clipboard && navigator.clipboard.writeText) {
        await navigator.clipboard.writeText(query)
        copySuccess.value = true
        setTimeout(() => {
          copySuccess.value = false
        }, 2000)
        return true
      } else {
        // Fallback for older browsers
        const textArea = document.createElement('textarea')
        textArea.value = query
        textArea.style.position = 'fixed'
        textArea.style.left = '-999999px'
        document.body.appendChild(textArea)
        textArea.select()
        const success = document.execCommand('copy')
        document.body.removeChild(textArea)

        if (success) {
          copySuccess.value = true
          setTimeout(() => {
            copySuccess.value = false
          }, 2000)
        }
        return success
      }
    } catch (err) {
      console.error('Failed to copy to clipboard:', err)
      return false
    }
  }

  /**
   * Copy all queries for a specific domain
   */
  const copyAllQueriesForDomain = async (querySet: QuerySet): Promise<boolean> => {
    const allQueries = querySet.queries
      .map(q => `${q.id}. ${q.query}`)
      .join('\n\n')

    const text = `Job Search Queries for: ${querySet.domainName}\n${'='.repeat(60)}\n\n${allQueries}`

    return await copyToClipboard(text)
  }

  /**
   * Export all queries as formatted text
   */
  const exportAllQueries = (querySets: QuerySet[]): string => {
    let output = 'JOB SEARCH QUERIES - Generated by Domain Finder\n'
    output += '='.repeat(80) + '\n\n'

    querySets.forEach((querySet, index) => {
      output += `Domain ${index + 1}: ${querySet.domainName}\n`
      output += `Role: ${querySet.technicalRole} | Industry: ${querySet.industry}\n`
      output += '-'.repeat(80) + '\n\n'

      querySet.queries.forEach(query => {
        output += `${query.id}. ${query.description}\n`
        output += `   ${query.query}\n\n`
      })

      output += '\n'
    })

    output += '='.repeat(80) + '\n'
    output += `Total Domains: ${querySets.length} | Total Queries: ${querySets.length * 10}\n`
    output += `Generated on: ${new Date().toLocaleString()}\n`

    return output
  }

  /**
   * Download all queries as a text file
   */
  const downloadQueriesAsFile = (querySets: QuerySet[], filename: string = 'job-search-queries.txt') => {
    const content = exportAllQueries(querySets)
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = filename
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  return {
    querySets: readonly(querySets),
    isGenerating: readonly(isGenerating),
    copySuccess: readonly(copySuccess),
    generateQueries,
    copyToClipboard,
    copyAllQueriesForDomain,
    exportAllQueries,
    downloadQueriesAsFile
  }
}
